# Generated by Django 3.2.3 on 2021-05-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('proveedor', models.CharField(max_length=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10000)),
            ],
        ),
    ]
